### ISSUE TITLE
Please split up into two packages

### ISSUE THREAD

**Issue by hvr** [ondrap/haskell-gssapi#1]
This looks very interesting and I'd like to use it (rather than reimplement one myself), however, there's a major blocker for me:

This package assumes a WAI interface (and incurs a package dependency on WAI & resourcet), both of which are undesirable to my use case (I use 3 different http server libs in my projects which are *not* based on WAI for good reason). Consequently, it would be ideal if this package could be split up into a generic `haskell-gssapi` and a WAI-specific `haskell-gssapi-wai` package, so that it would provide a naming scheme for other web-apis to provide mappings, e.g. `haskell-gssapi-snap`.

**Comment by ondrap** [comment]
Ok, I'll do that.

However, I am using `resourcet` for foreign pointer management internally - and I don't currently know of any better solution (`ForeignPtr` doesn't seem to fit the GSSAPI). But `resourcet` seems reasonably small - unlike `wai`, so that won't be hopefully a stopper.

**Comment by ondrap** [comment]
Done. I have renamed the package to `gssapi` and uploaded to hackage. Will upload `gssapi-wai` soon.

**Comment by hvr** [comment]
thanks!
